name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: NoteKeeper Frontend Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_HOST_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/Projects/notekeeper/frontend
            git switch main
            git pull
            cd /root/Projects/notekeeper
            docker compose --file docker-compose.yaml --env-file .env build frontend --no-cache
            docker compose --file docker-compose.yaml --env-file .env up --detach --build
          EOF
